version: '3.8'
services:
  # MySQL 데이터베이스 컨테이너
  mysql-service:
    image: mysql:8.0
    container_name: finance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "<password>"
      MYSQL_DATABASE: testdb
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  backend:
    build: .
    container_name: finance-backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
volumes:
  db_data:
