#spring.application.name=demo
spring:
  application:
    name: demo
  thymeleaf:
    cache: false
  datasource:
#    url: jdbc:mysql://mysql-service:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "<password>"
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:com/exam/mapper/*.xml
  type-aliases-package: com.exam.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.exam.mapper: DEBUG
