apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
  namespace: todo-app
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service.todo-db.svc.cluster.local:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_SQL_INIT_CONTINUE_ON_ERROR: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: springboot-app-secret
  namespace: todo-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: todo-app
spec:
  selector:
    app: springboot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: todo-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: cheongomabi/fs:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_SQL_INIT_CONTINUE_ON_ERROR
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_SQL_INIT_CONTINUE_ON_ERROR
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-app-secret
                  key: MYSQL_ROOT_PASSWORD